name: Chamado de Erro
description: Arquivo de Configuração de Chamados.
title: "[Chamado de Erro]: "
labels: ["Erro", "Análise"]
projects: ["octo-org/1", "octo-org/44"]
body:
  - type: dropdown
    id: cliente
    attributes:
      label: Cliente
      description: Informe o cliente o qual está solicitação a correção
      options:
        - 73550193 - WENDELL PEREIRA MATOS
        - 73550033 - Cliente Padrão Contabilidade
        - 73550080 - D&G STORE
        - 73550592 - Ana Karyta Martins Barreto
        - 73550593 - Paulo Andre do Nascimento
        - 73550594 - Time Easyren
        - 73550596 - HERR AGNES CERVEJARIA
        - 73550597 - Symom Castro
        - 73550600 - Toc Gas
        - 73550603 - PAPELARIA JOSY'S
        - 73550605 - DIV CONSTRUCOES
        - 73550354 - 3S ATACADO
        - 73550610 - Circuito Moto Pecas
        - 73550355 - BICHOMANIA
        - 73550611 - RENORTE
        - 73550356 - WM PARFUMS
        - 73550357 - MARCELUS
        - 73550614 - Renye Base Easyren
        - 73550615 - Mercosul Cosmeticos
        - 73550361 - BELEZA MAIOR
        - 73550362 - CACHO FLOR COSMETICOS NATURAIS
        - 73550618 - JALAPA ARAGUAINA
        - 73550620 - JM MARTELINHO DE OURO
        - 73550367 - NRD AGROPECUARIA
        - 73550623 - Colegio Invictos
        - 73550624 - Gabriela Oliveira
        - 73550625 - Lara Maria
        - 73550626 - VILHENA ELETRONICA
        - 73550116 - ARTE EM COPOS
        - 73550628 - Colegio Invictos Junior
        - 73550373 - COMERCIAL J & B
        - 7206 - CENTROCOPIAS
        - 73550632 - CASA RURAL
        - 73550638 - Refrigeração Nunes
        - 73550383 - DLARA MODA INTIMA
        - 73550643 - Construbarros
        - 73550389 - MAGO
        - 4919 - AUTOMIX CENTRO AUTOMOTIVO LTDA
        - 73550392 - NANDA KIDS
        - 73550650 - Hidro Park
        - 73550139 - GIGANTE ELETROMOVEIS
        - 73550651 - Pneus Extra
        - 73550652 - Hellem Caroline Silva Guimaraes
        - 73550653 - Areal Agua Doce
        - 73550398 - PAPELARIA CORES
        - 73550654 - Casa da Crianca
        - 73550655 - Universo Infantil
        - 73550656 - Rocha Car Premium
        - 73550146 - BELLA PLUS
        - 73550402 - RENOVAR AR CONDICIONADO PECAS E SERVICOS
        - 73550406 - BM LATAS & ACESSORIOS
        - 73550662 - IMPERIAL GAS LTDA
        - 73550663 - FIEL GAS
        - 73550410 - MARIA RITA BOUTIQUE
        - 73550666 - Karol Digital Boutique
        - 73550411 - ELCAMINAS
        - 73550667 - Supra
        - 73550413 - ELETROCAMPO
        - 73550669 - Lofty
        - 73550670 - Donna Store
        - 73550415 - GIGANTE COLCHOES
        - 6481 - DANIELLA DOURADO
        - 73550417 - RL REFRIGERACAO
        - 73550418 - ELEGANCIA EM ALTA
        - 73550163 - Fino Sabor Doce com Amor
        - 73550676 - Fernandes E Santos Fornecimentos
        - 73550421 - WE NUTRICAO ANIMAL
        - 73550677 - ZE E ZAH MODA INFANTIL
        - 73550678 - MARCELO MOTOSSERRAS
        - 73550167 - Demonstração Revenda EasyRen
        - 73550423 - NATHALIA GOMIDE ELIAS COSTA
        - 73550679 - NYLDE COSMETICOS
        - 73550424 - COURONORTE
        - 73550681 - 43.695.262 Felipe Eduardo Ruffino Benevento
        - 73550682 - Rafa Bike Shop
        - 3675 - DESIGN INTERIORES
        - 73550171 - JOAO E MARIA MODA INFANTIL
        - 73550686 - M B LATAS & ACESSORIOS
        - 73550687 - 52.630.451 LANNA BARROSO FERREIRA NOBREGA
        - 73550432 - DESIGN MOVEIS E DECORACOES
        - 73550178 - TOCANTINS ORDENHADEIRAS
        - 73550434 - ENCANTO DA MODA
        - 73550180 - COLCCI
        - 73550693 - JHON BARBER SHOP - UNIDADE 3
        - 73550695 - Natoflex
        - 73550442 - NORTECAJUS
        - 73550444 - DR TERERE
        - 73550445 - LIFTER
        - 73550701 - Arte Vasos II
        - 73550702 - Cna Agronegocio
        - 73550705 - Dias e Sousa
        - 73550450 - JANAINA VARIEDADES
        - 73550706 - 55.324.397 ELZIANY AQUINO COSTA
        - 73550451 - GIOVANNA FLOR
        - 73550197 - EXTRABOM
        - 73550710 - Agrotecnica Locacoes
        - 73550711 - Água de Coco Tocantins
        - 73550456 - AGROROLFI REPRESENTACOES
        - 73550457 - PRISMA FERRAMENTAS E FERRAGENS
        - 73550713 - Aguia Mix
        - 73550202 - ATACADAO DOS BONES
        - 73550459 - MILLA MOTOS
        - 73550715 - Imperio Calçados
        - 73550204 - BRILHO DE SOL LINGERIE
        - 73550716 - Agrocampo
        - 73550717 - ALANA MODA MIX
        - 73550462 - Mauricio Santana Ribeiro
        - 73550720 - Carijós Assados
        - 73550721 - FC PINTURA E LANTERNAGEM
        - 73550466 - W G Construções
        - 73550722 - 3A Reciclagem de Metais LTDA
        - 73550467 - LIMPISCINAS
        - 73550723 - KSA COLCHOES LTDA
        - 73550724 - R F Imports
        - 73550726 - Sorvete Italiano
        - 73550729 - Couto Store
        - 73550475 - POWER SOLARE
        - 73550731 - Elis Vitoria da conceição
        - 73550732 - Mari Makes e Acessórios
        - 73550221 - MORENA FASHION STORE
        - 73550477 - Teste Paulo EasyRen Fantasia
        - 73550733 - Steel Tech Equipamentos
        - 73550734 - Rc Tech Distribuidora
        - 73550223 - TORNADO MOTOS
        - 73550479 - VENTURA MATERIAIS PARA CONSTRUCAOCA
        - 73550736 - Olpe Colchoes
        - 73550737 - Joabe Porfirio Pereira
        - 73550482 - SINTONIA MOTOS LTDA
        - 73550738 - Victoria Joias
        - 73550227 - JABOTA STORE
        - 73550484 - ANAMODAS
        - 73550740 - CENTRAL DO IPHONE LTDA
        - 73550741 - Ms Acessorios
        - 73550486 - se vira nos 30
        - 73550743 - Lojão Goiano
        - 73550489 - KAMI
        - 73550746 - 57.618.594 RENATA COSTA MACEDO
        - 73550236 - VIP AUTO CENTER
        - 73550237 - CASA DECOR
        - 73550750 - Modernita
        - 73550751 - Jose Lanevon Ferreira da Silva
        - 73550752 - TODA CHICC LTDA
        - 73550241 - BRILHO DE SOL LINGERIES
        - 73550754 - FLOR DE MAGNOLIA COMERCIO VAREJISTA DE JOIAS LTDA
        - 73550500 - NRD AGROPECUARIA EIRELI
        - 73550756 - Maciel Motos e Bicicletas
        - 73550245 - Rga Comercio de Alimentos Eireli
        - 73550757 - Euro Materias Para Construcao
        - 73550758 - F.J.S.DISTRIBUIDORA DE ACAI LTDA
        - 73550759 - FIRMINO E LIMA LTDA
        - 73550760 - 55.420.667 GABRIEL DIAS CIRQUEIRA
        - 73550761 - R D DUARTE LTDA
        - 73550250 - R H R RAMOS EIRELI
        - 73550762 - FLOR DE LIZ CONFECCOES E VAREJO LTDA
        - 2731 - C DE LIMA BARRETO EIRELI
        - 73550507 - MALURY COSMÉTICOS
        - 73550252 - PHINFO SOLUCOES EM TI
        - 73550513 - COMERCIAL MARANHENSSE
        - 73550514 - VIP ESTETICA AUTOMOTIVA
        - 73550260 - GUERRA ARMAS E MUNICOES
        - 73550516 - DM BEACH WEAR
        - 73550518 - SMART PROJETOS E EXECUCOES
        - 73550519 - CASA DAS BATERIAS
        - 73550264 - CICLO BIKE
        - 73550520 - IMPOR TATICO
        - 73550521 - Auto Pecas e Oficina Renascer
        - 73550522 - PANIFICADORA PAO E CIA
        - 73550523 - Reino Criativo
        - 73550014 - V CAMPOS MOVEIS
        - 73550526 - Lorranny Gomes
        - 73550527 - PAPEL E PILOTO COMERCIO E SERVICO LTDA
        - 73550528 - RESTAURANTE FOGAO DE LENHA
        - 73550017 - ECO BIOS COMERCIO E PRESTAÇÃO DE SERVIÇOS
        - 73550274 - MADIANN OUTLET
        - 73550530 - WM METAIS LTDA
        - 7108 - LANCHONETE & PIZZARIA SHALLON
        - 73550020 - Mais Bela Modas
        - 73550277 - LAERTE CIA
        - 73550278 - PAPEL MOEDA SEMIJOIAS
        - 73550534 - AR ELETRICA ELETRICIDADE E REFRIGERACAO
        - 73550279 - VD IMPORTS
        - 73550280 - REFRISERVICE REFRIGERACAO
        - 73550537 - LASERTECH INFORMATICA AUX
        - 73550027 - COMERCIAL DOM ORIONE
        - 73550540 - JHONATAN LENNON CARDOSO DA SILVA
        - 73550541 - SHOP LUGAR CERTO
        - 73550286 - LOBAO TRUCK CENTER
        - 73550542 - OLD SCHOOL PECAS
        - 73550287 - CASA DE CARNE MATHEUS
        - 73550543 - Distribuidora e transportadora Ideal ltda
        - 73550032 - BIKE SILVA
        - 73550546 - GAS BAT CUSTOM
        - 73550548 - DELTA SERVICOS E LOCACOES
        - 73550293 - SUPER ROCHA
        - 73550553 - MAMEDE IPHONES
        - 73550042 - SOLUTEC INFO - SOLUÇÕES EM INFORMATICA
        - 73550554 - FAZENDA SANTA TEREZA
        - 73550301 - A HOSPITALAR
        - 73550046 - ARTE & VASOS - ARTEFATOS DE CIMENTO PARA JARDIM.
        - 73550303 - MAURO BATERIAS
        - 73550307 - MASKAVO DOCERIA ARTESANAL
        - 73550564 - A W MONTAGEMS INDUSTRIAIS LTDA
        - 73550310 - THE CLOSET MODA FEMININA
        - 73550312 - MB AUTO CAPAS
        - 73550313 - GAS AMAZONAS
        - 73550314 - LOLLI STORE
        - 73550570 - Catharine Concept
        - 73550315 - TM IMPORIUM (PRIME CALÇADOS)
        - 73550316 - STUDIO FITNESS
        - 73550575 - FLORICULTURA MORAIS
        - 73550577 - VR VARIEDADES
        - 2034 - LP TECH CELULARES
        - 73550322 - LAZULI
        - 73550578 - MILENA ADESIVOS
        - 73550579 - EP-EMPILHADEIRAS PAULISTA
        - 73550327 - J R ALENCAR DISTRIBUIDORA DE FRUTAS E VERDURAS
        - 73550584 - FRIGORIFICO LIBERDADE
        - 73550329 - R&A imports
        - 73550586 - POUSADA E RESTAURANTE RECANTO DO LAGO
        - 73550332 - JHON BARBER SHOP
        - 73550589 - COMERCIAL SOUSA
        - 73550591 - gusthavo
        - 73550604 - DESK CASA
        - 73550636 - C & M PARAFUSOS
        - 73550639 - DOCES JOELMA
        - 73550640 - lider parafusos
        - 1893 - Glaucia Moda Intima
        - 73550448 - LS CONTSRUÇÕES
        - 73550704 - IZABELA BRUNA DE ARAÚJO
        - 73550708 - JANE JJMAISON
        - 73550718 - TUPA ELETROMOVEIS
        - 73550728 - TUPA MASSAS
        - 73550739 - EDILUZE DECOR
        - 73550742 - GRÁFICA CRIATIVA
        - 73550748 - NAP SERVIÇO
        - 73550749 - NAP ENERGIA SOLAR  E ENGENHARIA FILIAL
        - 73550755 - KL PNEUS
        - 73550012 - KEITA PLASTICOS & ARTEFATOS
        - 73550271 - NAP ENERGIA SOLAR E ENGENHARIA
        - 73550538 - STUDIO GIL LEITE PERSONAL
        - 7378 - Industrial e Distribuidora de Gesso Santo Antonio
        - 73550582 - APLAUSOS ARTIGOS DE DANÇA
        - 73550633 - NOELY MACHADO GONÇALVES
        - 73550573 - DISK67 CONVENIENCIA
        - 73550580 - MNETTO COMERCIO - SERVICOS
        - 73550692 - AGROPET
        - 73550698 - M. C. A. MOREIRA RESTAURANTE E EVENTOS
        - 73550700 - ABS FERRAGENS
        - 8072 - Brazil s Natural Secret
        - 73550744 - E L IOP AGROPECUARIA LTDA
        - 73550747 - HIDRALICA CERTA
        - 73550255 - Aromas da Terra
        - 73550007 - MERCEARIA SENA
        - 73550609 - CRIATIVA PRESENTES
        - 73550363 - BOXRR7 ARTIGOS ESPORTIVOS
        - 73550115 - CANAA BIKE SHOP LTDA
        - 73550634 - Wm Closet
        - 73550379 - GMX UTILITIES
        - 73550635 - MY BRAND BOUTIQUE
        - 73550668 - LAZER EMPREENDIMENTOS
        - 73550672 - N Y LOCACOES
        - 8545 - Imobiliaria Franques e Lira Ltda
        - 73550697 - ESTRIBO
        - 73550709 - FERRPAV TERRAPLENAGEM E PAVIMENTACAO
        - 73550714 - BIKE SHOP CARAJAS
        - 73550727 - WENNIA ALCANTARA NASCIMENTO
        - 5769 - M M CONSTRUCOES
        - 6549 - Primicias Distribuicoes e Servicos
        - 73550539 - DISTRIBUIDORA NUNES LTDA
        - 73550041 - A da R Silva Eireli
        - 73550590 - AGUIA DISTRIBUIDORA
        - 73550485 - COMERCIO E ACOUGUE TODO DIA
        - 73550488 - Fazenda Santo Expedito
        - 73550490 - FAZ MATERIAIS PARA CONSTRUCAO LTDA
        - 73550497 - RAGAS COMERCIO DE RACAO E GAS
        - 73550498 - ELETROAR
        - 73550505 - INFINITY STORE
        - 73550158 - JOLIE STORE
        - 73550707 - RENAN DENNER GARCIA VIEIRA
        - 73550622 - 20.698.966 LUIS GONZAGA MAGALHAES LIRA
        - 73550153 - OPÇAO MODAS
        - 73550154 - GAS E AGUA BRASIL
        - 73550691 - LUZENY MODAS
        - 73550212 - WILSON RIBEIRO DE FIGUEIREDO NETO LTDA
        - 73550481 - O P DOS SANTOS COMERCIO DE BICICLETAS
        - 73550343 - CICLOVILA BIKE E MOTO
        - 73550358 - VOLVAÇO MECANICA LTDA
        - 73550377 - OFICINA DO EDMAR
        - 73550719 - BY NIGHT LTDA
        - 73550213 - MARISLENE P. BAIA MOVEIS E ARTIGOS DE DECORACAO
        - 73550476 - Churrascao do Marcao
        - 73550480 - Loja dos moveis e decoraçoes LTDA
        - 73550231 - TOTAL MOVING EXPRESS
        - 73550232 - MPR ARTIGOS E VARIEDADES
        - 73550242 - MARLENE MACHADO DE SOUZA FRANCO
        - 73550267 - SAMUEL AURELIO LUCIANO
        - 73550268 - SIRLEY DE SOUZA 06840958663
        - 73550270 - ENXOVAIS DELTA
        - 73550282 - EDIMAR PATRICIO BARBOSA 05982897639
        - 73550333 - ESPETINHOS E CALDOS PAULINHO
        - 5071 - Catarina Modas
        - 73550325 - ALEXANDRE HENRIQUE SARTORI
        - 73550696 - CONTEMPORANEA MODA MULHER LTDA
        - 73550725 - JORDÂNIA PERFUMARIA
        - 73550735 - GLAU
        - 73550745 - SHOP DAS CALCINHAS
        - 73550571 - WS PRE MOLDADOS
        - 73550685 - R DE C P ALENCAR
        - 73550688 - J A LUTIFI SEGUNDO LTDA
        - 73550730 - BRAGA MOVEIS LTDA
    validations:
      required: true
  - type: textarea
    id: descricao
    attributes:
      label: Qual o problema que está ocorrendo?
    validations:
      required: true    
  - type: dropdown
    id: produtos
    attributes:
      label: Produto
      multiple: true
      options:
        - ERP EasyRen
        - API MD-e
        - API PIX
        - API Boleto
